[app]
  http_port       = 8181
  log_component   = "start"

[datasource]
  name                = ""
  access_type         = ""
  username            = ""
  password            = ""
  schema              = ""
  [datasource.options]
    host              = "localhost"
    timezone          = "+08:00"
    dialect           = "mysql"
    [datasource.options.dialectOptions]
      decimalNumbers  = true
